### ISSUE TITLE
(feat) Alert before paste & screenshot history

### ISSUE THREAD

**Issue by kodbilenadam** [ekqt/screenshot#1]
Hi! 

I stumbled upon your project in the dev.to comment section. But while using it I had to switch tabs when I accidentally copied an image it was pasted without asking anything.

It would be nice to see a popup if changes were made to the current image and never copied or downloaded. 

Also, it would be nice to have a history of the last 10 screenshots at the bottom of the page. While doing research sometimes there were times that I had to go back and find the thing I was looking for and screenshot it again. 

If you are open to accepting PR's I can start working on these features but my front-end knowledge a bit rusty 😄 

PS: Great work with the project!

**Comment by ekqt** [comment]
Hey @kodbilenadam ! Thanks for submitting this issue! I originally implemented the "click here to paste your clipboard" functionality but I wonder if it would be best UX to enable a button and/or a shortcut instead (ctl + v), wdyt?

Regardless, if a reset is detected, a toast would be nice. PRs are welcomed, I can help with the UI if needed, huge thanks for trying out the Screenshot tool. 🙏🏼

**Comment by mateusabelli** [comment]
> I'd love to figure out if there is a way to store these images locally as some Users might have privacy concerns about this.

Hello @ekqt I've never done this before, but I think that you could convert the image to Base64 string and store them in local storage. This way the image is available only on the users browser cache and the app can consume them by accessing local storage and converting the Base64 string back to an image. I hope this helps!

**Comment by ekqt** [comment]
@mateusabelli thanks for the info! I'll log a separate issue and reference your comment! We're open for PRs so if you'd like to give it a shot you're more than welcomed!

**Comment by ekqt** [comment]
Closing this issue to address separately. Will add both of you as contributors for ideas! 🙏🏼

**Comment by ekqt** [comment]
@all-contributors please add @kodbilenadam for ideas
