### ISSUE TITLE
Failed to Contact `turbod`

### ISSUE THREAD

**Issue by ekqt** [ekqt/screenshot#17]
There seems to be an issues while using Turbo https://github.com/vercel/turbo/issues/2034

```
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
	- the process identified by the pid in the file at /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.pid is not running, and remove /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.pid
	- check the logs at /Users/hectorsosa/Library/Application Support/turborepo/logs/25b12ed5a16fdb56-screenshot.log
	- the unix domain socket at /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.sock has been removed
	You can also run without the daemon process by passing --no-daemon
```

I tried a couple of the things mentioned here with no luck. CC @kodbilenadam

**Comment by kodbilenadam** [comment]
This is not an issue but a warning with turbo because in some cases turbo is not able to run daemon process. This could easily bypass with `turbo dev --no-daemon`. Turbo runs perfectly fine with `turbo dev` but it gives out error. 

There are temporary workarounds for this warning such as:
- Running turbo with sudo
- Removing cache & Temp folders.

But safe to say running turbo with passing --no--daemon would be best way to go until Turbo fixes this issue.

**Comment by ekqt** [comment]
Yeap, I read the same in the comments. Should we create a PR to update our `README.md` and add these notes for development?

We can update here: _3. Start the development server,_

We can leave the normal code block and add below the option for running turbo with a comment for the warnings.

**Comment by kodbilenadam** [comment]
> Yeap, I read the same in the their GitHub issues. Should we create a PR to update our `README.md` and add these notes for development?
> 
> We can update here: _3. Start the development server,_
> 
> We can leave the normal code block and add below the option for running turbo with a comment for the warnings.

Let's create a PR to update `README.md` running with Turbo.

**Comment by ekqt** [comment]
@kodbilenadam maybe you know this already, but if not good to know, whenever you open a PR, if you use the keyword **Fix** or **Closes** (I like closes) followed by the issue number on the PR's description. It automatically closes the issues once the PRs are merged.

**Comment by kodbilenadam** [comment]
> @kodbilenadam maybe you know this already, but if not good to know, whenever you open a PR, if you use the keyword **Fix** or **Closes** (I like closes) followed by the issue number on the PR's description. It automatically closes the issues once the PRs are merged.

Oh I didn't know that! Will definitely use it in the future.
