### ISSUE TITLE
Add Info Tooltips to Settings

### ISSUE THREAD

**Issue by ekqt** [ekqt/screenshot#5]
Some users might be confused as to what each setting does. Right now we have pretty basic stuff but it would be great to have tooltips explaining what each of these settings do.

**Comment by kodbilenadam** [comment]
Should we use https://ui.shadcn.com/docs/components/tooltip for this one?

**Comment by ekqt** [comment]
Yes, all of the components here are taken from Shad's library. The only thing is that we're sticking to colocated Tailwind colors for now, so you need to make sure none of them rely on CSS variables and they are all consistent to then component we have.

I'm scouting to get help from a Designer but for now, we're keeping it simple.
