### ISSUE TITLE
Set the cursor to pointer while hovering over sliders

### ISSUE THREAD

**Issue by alefDev-prog** [ekqt/screenshot#6]
Maybe it would be better visually if the cursor turns into a pointer while hovering over the padding-sliders

**Comment by ekqt** [comment]
Great suggestion, I see that the rest of the elements do have this with exception of the input type color picker and the sliders. @alefDev-prog would you like to open a PR for this?

**Comment by alefDev-prog** [comment]
Hi, yes I can do that
